base: /
disableStaticFileCache: false
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=53'
languages:
  -
    title: Deutsch
    enabled: true
    locale: de_AT
    hreflang: de
    base: /
    websiteTitle: ''
    navigationTitle: Deutsch
    flag: de
    languageId: 0
  -
    title: English
    enabled: true
    locale: en_US
    hreflang: en
    base: /en/
    websiteTitle: ''
    navigationTitle: English
    fallbackType: strict
    fallbacks: ''
    flag: en-us-gb
    languageId: 1
rootPageId: 1
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: /
    index: ''
    map:
      /: 0
      sitemap.xml: 1533906435
txCsseoXdefault: 0
websiteTitle: 'Hotel Alpenblick'
